apiVersion: extensions/v1beta1
kind: Deployment
namespace: {{.Values.namespace}}
metadata:
  name: resource-planner
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: resource-planner
    spec:
      serviceAccountName: resource-planner
      nodeSelector: 
        workerNode: "yes"
      containers:
      - name: resource-planner
        image: arguez/matrix-generator:latest
        imagePullPolicy: Always
 
       
